# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/orbital',
                'doc_host': 'https://the-engi-nerd.github.io',
                'git_url': 'https://github.com/the-engi-nerd/orbital',
                'lib_path': 'orbital'},
  'syms': {'orbital.core': {'orbital.core.foo': ('core.html#foo', 'orbital/core.py')}}}
